on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Set API key
        run: |
          if [ -f "config.yaml" ]; then
            echo "::debug::config.yaml exists"
          else
            echo "::error::config.yaml is missing"
          f
